/*
 * Copyright (c) 2021 Hai Zhang <dreaming.in.code.zh@gmail.com>
 * All Rights Reserved.
 */

package me.zhanghai.android.files.compat

import android.webkit.MimeTypeMap

// Generated by mime/generate-extensions.sh and mime/generate-code.sh .
private val extensionToMimeTypeMap = (
    extensionToMimeTypeMapData1 + extensionToMimeTypeMapData2 + extensionToMimeTypeMapData3 +
        extensionToMimeTypeMapData4
    ).toMap()

fun MimeTypeMap.getMimeTypeFromExtensionCompat(extension: String): String? =
    extensionToMimeTypeMap[extension] ?: getMimeTypeFromExtension(extension)
